/* eslint-disable react/jsx-props-no-spreading */
import Head from 'next/head';
import React from 'react';
import type { AppProps } from 'next/app';
import '../styles/globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function app({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Herzenswünsche Allgäu e.V.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
